name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff semgrep

      - name: Lint
        run: ruff check .

      - name: Docker build (no push)
        run: docker build -t auth-api:ci .
      
      - name: Semgrep scan (non-blocking + SARIF)
        run: |
          semgrep scan --config p/ci \
                       --sarif --sarif-output=semgrep.sarif || true

      - name: Upload SARIF to GitHub Security
        if: always() && hashFiles('semgrep.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
